# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tti
    REF boost-${VERSION}
    SHA512 c89b3d305a13cf1fe3922040632ff4e2fbf20f8c83a4f10d43bb0f88328953f7e2452d5624c9e76aaaf1abfdb944b5a5307cb3ff4c3771ae1faccb0104221379
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
