# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/phoenix
    REF boost-${VERSION}
    SHA512 379cc1b9b2866ac379ba1d259ce4cf036623daba63bb0599815128030e766c19e92f95514e08346ac0f638e050e2e00eaf058d1ce5d7701586d897e5b0c96e95
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
