# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_traits
    REF boost-${VERSION}
    SHA512 13cac538d2f79eccfb61147701cc2edc6b326396beca2f1c7ef315d67205a40fcbec119525a1b8fb4770bde660619639817e4788289677dc8694d992bd838dcb
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
