# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/align
    REF boost-${VERSION}
    SHA512 1c76c2ab2fc44bddcb96c6e5335fcb0fbae46ce602dfdf93285a057b5d3439fb132e36d20f96474dbfea41748dfc3e46bba019252f9d5ea5620809f5d61f892a
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
