# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/align
    REF 5ad7df63cd792fbdb801d600b93cad1a432f0151
    SHA512 a24c0340fec475592c5aa55c9ba40b7824a0402dd521ccff4b123c8ed95917fc6e44f0fb03edecb27dd5ac61a6a5aad6647ec60089f34ecdb0aca166ba12a2ae
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
