# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/contract
    REF boost-${VERSION}
    SHA512 122fd0d20840f9beb824ac75b2d564326576dcbfb3b8ab9b92b361620bbb1ccd70d3b358e530c1f0b79995c5358d5ffb08c2f7c6d9349e5f9ca6a7ba00b21d88
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
