# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tuple
    REF boost-${VERSION}
    SHA512 7e5dac83cb250e99aa09f4e74104e8c20c90901d14f5b0fac45d9efe40948451d391d07bbed6766c15c492a4a9e515da0cc1f82b9dcf29c6bd0644399c7c40b2
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
