# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/functional
    REF boost-${VERSION}
    SHA512 3669ca8aa4c3a1987bd08641705cb43637ee628f4111b584f9afea4b1b68c23e5cb79a5d3bb9435c7db606d32acc0f2f99e753a83e7d9a624cdbab0bad718803
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
