# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/exception
    REF boost-${VERSION}
    SHA512 01cccdaa247de03fb17ec87900803c181baac8a97733683754c2f20e969bbe1e562593b2ad0fbe66ac93d07ddc85f4f9e440122164aacfaac54201c04aa5128a
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
include("${CMAKE_CURRENT_LIST_DIR}/features.cmake")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
