# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/callable_traits
    REF 2a56a3a2496cdb66496f844db55085dd992d5e49
    SHA512 3dea93793270baa97292bb4dbcbe5f0be1a52db33fa2f0a6af3ef89c17a23a780b18554f36361564e43970b0154e73a4c840a50b97f11f1ff05356f79d1de037
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
