# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/callable_traits
    REF boost-${VERSION}
    SHA512 a47132f8cb0d128e9596c6ce60c6844b2ab17513f87a85c1dd9f138a917b969103e8c17666ccc85847a93f01f5f1d407432e0700c629f84793e66c6c16deafdc
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
