# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/throw_exception
    REF f3d4d55f52894fda75ef2915dc122e3133b97b45
    SHA512 cd02589380d50e3d4889124058a9920b0e91965016bbfb9a6f924463461d52fef931c0e74b0c1a00fb352835808d37c8227c20ee508df458470aaf153abd8737
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
