# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/stl_interfaces
    REF e60873635eb2a4f699daee0f721d5f3cb041e826
    SHA512 95f5e73c43ec5c5f1657262441edbb47f4c9e3ca07e712187a988d0b9549e4228a45190ca1876018516a1cf2d73268580068c43fa2ff373d041a0e90285be7b3
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
