# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/stl_interfaces
    REF boost-${VERSION}
    SHA512 0177c6a25717cee2c29054b071e1ad6ba1630c3adbe6674ed0c20b121417c1f4128f788bb86ae470b94d4f9e2f2fd623bbb823fd3a29825cd5d20a397d2ec5b5
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
