# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_index
    REF boost-${VERSION}
    SHA512 ce3958f8b4549ce199183378c3d65d4c630bd1752d9b190b84cefab87b789dc9312e18b274abfe9cb15fbd0db211cd7f11bc6993a9ad424a625817f0e03f7c0b
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
