# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_index
    REF 14ee2581bdcaba85a0c3a61f8d1527e5425ed84c
    SHA512 d9f0147688e91595451e8b42254219f78c226a81562b253d65436e0bf16a88bdecf15906793bc702cc83341c400dfa03df7c7093f418dcd487fca493f986a539
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
