# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/smart_ptr
    REF boost-${VERSION}
    SHA512 1d55e1ca7f9ba9cec1361229b983e96366ea110ed43fcc3b4849e2269755deaa73b385b884c0ea9254c5ca82bf25f655bd9477d4c391d241b2f89cc01c506a8a
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
