# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/smart_ptr
    REF 0b0924ff82ba78c1e6c89965abadb6fae109a4e3
    SHA512 7b2873486d3b7e5936b5c05348bfcea8ad80fc192d1b6e1b274c530300103792a14ba6bbed5057c130721d9bfbba321f5a0c110741c037e08ca9a809b2d0c49b
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
