# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/stacktrace
    REF boost-${VERSION}
    SHA512 708f52eb3cee64b298d55485bfb8899b199797a2f5481e589ff0377f886d7fdfe440eb90ab3cdfdca66cd89249babf5b825ff4f095eccebd4e53e951f3ece667
    HEAD_REF master
    PATCHES
        fix_config-check.diff
)

set(FEATURE_OPTIONS "")
include("${CMAKE_CURRENT_LIST_DIR}/features.cmake")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
