# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interval
    REF boost-${VERSION}
    SHA512 821c1531df390405f7623cd9ced8d66f112e05cc3244ae15e95fa1bcc6b4529c17b507e6871a7e9edc624f38dd0da04f7fb73ac26af5ecebc46ed884f88cf684
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
