# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/serialization
    REF 8a8c62864f05732131bf6785d54466d8ac6cd477
    SHA512 71768f18df904693e8e25d839cd889b61eb577f29014a0cf11997dcf8bf17d710cc0f1c3986b1cdbfed573236459ced95697acc44c6dba31bcb49af50430eb62
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
