# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mqtt5
    REF 5375062894f192351d2827e33412179471e01113
    SHA512 9c17adcd630b744c296821a2fa3bb7d36869997b8191d3f464a3f35848eaf95d40147c90f8b1b5132344353cbf7c79295f31ef35d8b3a465223191bbb738d8d8
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
