# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mqtt5
    REF boost-${VERSION}
    SHA512 6ed8999e2b0bf2bd0ea3838adbd8bee88623cdf70fb7ce06ea598907aa913490c4db1f2ad95e74871b396450c0a57d2db3fea0ed30aef9c4aa808a01f972e056
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
