# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/utility
    REF boost-${VERSION}
    SHA512 e02ab03e5d88136d820434e2bf0212e64ae66f226e1938acf16bdd6c653ab764c03e571a0bbf3eb720bfb9b220d7e56c5d6766f9d31b0627a22ca8ff2d36f615
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
