# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/python
    REF f604eb8d0f99f5c16831cd4ccd86d9edc859c189
    SHA512 af2878e63c367f179b75026e0ad945d016a67786e0ace5853a618b386ae41a098a7be3da3e306e797435db1c171d998cab6d0f0803a0146b59c4b5f46ef26105
    HEAD_REF develop
    PATCHES
        remove_undef.diff
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
