# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/python
    REF boost-${VERSION}
    SHA512 7d049272b7c558fc157ee4809ed1cacd6033270580f271495aaca9a0822ae024189322c8cf5c46a68d4fc4cfb1570897efa22f7256fd7fd1f44128aab7b40543
    HEAD_REF master
    PATCHES
        remove_undef.diff
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
