# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/random
    REF 7363de5e94a524822cd26e04767b84690cca94b1
    SHA512 919235364467593e91263ef02824c3bbd7e834b8017c4b1f0ac88b3e8ee1f1001784ef3ab155ce770a5767fbc90874f931919aa9b49c665876410fbf53baf25f
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
