# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/random
    REF boost-${VERSION}
    SHA512 e9df49016378503077bf2ec35439643748d02efe7dc818a8017a09bf399e61da0934263b24dd87af354f5a0ba13585ea8baff0b9905e236a2164f13ceed8c7c9
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
