# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/fiber
    REF 238487b543e8863c647d31a82ccfc3fa11a960d9
    SHA512 f3e9cce37cd8508284c68c89036eb65864eddec0dc680de582d8fdcd1df4b6a4f46d334906229e0a00337022aff1f1f4586ac3ee0d6866ea8f7a0bb5df9e9708
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
