# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/fiber
    REF boost-${VERSION}
    SHA512 72553574f39f625a8c02a07b278c8c49afae6aa3b1e76b881f85d79bd8c8d64d848f760aabb9c8f650c7b7c0b8bb00df7dcfd90b6a35fef37ce3ae1b6eb70692
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
