# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hana
    REF boost-${VERSION}
    SHA512 dbcfb517b051518859f2446beb63ab13a76e3525ebae9c6c6012ac4cfda620ca7b132889e221537c91cc828578d0184c75936b2f992ebd3b15888384d3b12ddd
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
