# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/array
    REF e988ef9c4a7d64be2850dc8de18b6461e094d4ae
    SHA512 b659f44f0b7bacb9f4c08adee63b2f3968fbcfda1046beef5cb0c488e8329d3117ae55e5bb5138b5848a47614351420c5cf875dcdd0089708c70222d1f4c91f5
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
