# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/array
    REF boost-${VERSION}
    SHA512 9ef22ab3944a478245b7df0f5d17f019654ceb6aca3603c736535d4d85a26f1c051651de42d74fda80828673bbb42fa3f91c08a0a30e81b9ad6f711be194ab2b
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
