# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/container_hash
    REF boost-${VERSION}
    SHA512 77ce08dfcf090f003dbbc8b259251002f3b3c283453398581df8792fd4f9814d8b5c133e8de10abeae71b58038e00facea9577a9c4bfe651dc9eee775cd48fc7
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
