# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/uuid
    REF boost-${VERSION}
    SHA512 684a40562e41a4f97771c6cef3af655bd4b1c8dc05f6324a094a02cd6462c5616b4cd0b15977c247c43f9ad4f339bda3aacd11491c99cecca5a034b2b5804c44
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
