# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/uuid
    REF e7f4cebe81835fd1b5558178f3d4c40ae266d8e2
    SHA512 7ac8427130fed82e93f95066931317857975b8362d8bc1485ff0b40edddc86c7694c96b7b1124480b6e80c487ad38b89737532c79f4565a9847e36c2fe372d91
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
