# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ratio
    REF boost-${VERSION}
    SHA512 659c98a06b1c6e5dd2274cce85230a2657cf232704e494e697e7dec1af5c2d46e07736616b7791561a744b0cf63860c393c497a3a25339f1b47ebd411981fa9c
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
