# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lexical_cast
    REF boost-${VERSION}
    SHA512 d89afe2565ed3df3f85b7bac5f3403f39af04b21dc659e92cbefc207e6cd6389b4670590fa08c75348c5b4065e1c0c3724adab7d3f45656019d78d1648ae9a54
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
