# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/atomic
    REF 199906f4e1789d8d182d478842ea4df9543d5fea
    SHA512 b646f4eee98eff0924066868a0a0f989417b3bf556ace1e1c6364dc6045a76aa2386b8392c2683ca6e3205c60a94a088d0094e22043836a64f420740f34aea88
    HEAD_REF develop
    PATCHES
        fix-include.patch
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
