# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/asio
    REF boost-${VERSION}
    SHA512 bd17c014674040d7daf2bc856e3cb236a1ec7359d41c82f22c43672229fce9254a210fe332426f91305d80f2bc275d82e9758356ef376ee2f002bd4f9ef4d48f
    HEAD_REF master
    PATCHES
        opt-dep.diff
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
