# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/iterator
    REF boost-${VERSION}
    SHA512 1295168cad716c3439bb28c75ce4a1e9235f9c1196c5ed4a20417dd131964650eb5bcb9985f31ec4de371a8c9eef4fd8eb8cf7967df0f01ca70e23291ff3fabf
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
