# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/iterator
    REF c2b846c57dd0bce0f7ab2c91b883e3b9ce423ceb
    SHA512 99e20d8364ce444401cd64387c83d4e7ddb021336e9039eb8ec9e387a3e052479a443c0d89d5d9a01a725e7fec60096373e472d2eb53c0392c7aac79585e6a4d
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
