# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/program_options
    REF boost-${VERSION}
    SHA512 321e71120c26c0be44caadc1d848f43f2494fd68a2117eede944b003159f8c5523d29c5e6939664e1ab125267e349b1ec066d00da0af361044b607b66458f75e
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
