# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/variant2
    REF 8caa1a34843951b9e4e302dc85e90bc19ca4f3dd
    SHA512 afc652b3e70df12eecdc2af82f557dd50ac71e3fe76fca661fec44fae55fad9fdbeb2247e599cd45cf9e0d5516c191b1bf46fb6f1e996057d3c50533cd62c675
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
