# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/variant2
    REF boost-${VERSION}
    SHA512 33cdef588f88a59ed0da0b62cbb9759db1dab738f4a5ccd9bf4b3852c68f7a33972db55f95a6d1deb20c4b729429e74644dafff69477d06b761317d349939552
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
