# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/msm
    REF boost-${VERSION}
    SHA512 4ccd258ca8298513763fd52cf3fad7299432b1e934801aafc092327797cb720863db2cbc5f0ec76084f88ce4f061fab7db22df9db5d7dca9a42bb4e9c67be097
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
