# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/msm
    REF 33e77cbfc70956d4b99f3dfc9c1e83848fe2550b
    SHA512 9e18af1b56426033395c5d127fce8239acf28c924d5b49de395c1f4eb708ea0a7fcce46383d867338ed5065890de537311a51f569848ab05fd5a727278ee16a6
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
