# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/intrusive
    REF boost-${VERSION}
    SHA512 93f30dfd55887cca3d9b8a38b1a8babffe3c29185774d42bd2096a2962930c60836fdbdf7e970a779eb9309a80ccebd6bee15d38702841e1a600e521a37bf4ad
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
