# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/intrusive
    REF e3d04834a504657f7672fefb4b6f515b17e8777e
    SHA512 24dcb0956d137b04368ff9baed036abfe18890231ccbf4b7a0acf3ba819976c4fae504afb69fa3fc2a3ce55c88c21f9842d957300396c3421f327ec0d1cad7d0
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
