# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/parameter_python
    REF boost-${VERSION}
    SHA512 74efedc5545e832a15d4b77244bd3f22eccd7c4bc92ff1f47d83560c200f19db5c55386e4a0d25db8a295f2d03c680293ad9d2119ae16be4992aa7fca799a31a
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
