# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/numeric_conversion
    REF boost-${VERSION}
    SHA512 f3a6130346a2b08b3e4554813e5964b5e603364a09b0907890f2c7e19804ab016289cd169ae5759e9905ce6665215aa960f96c41e1f908660ef5983aaa75c1c8
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
