# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/coroutine2
    REF boost-${VERSION}
    SHA512 048f4ae98038371aea0d6961ba9cd04ee09e8b1b0ac52862c0213f91344922b4b5e88d647f7f18eca88e3ac1409e7ef9dc1b694aab39f7bc613bf7c979085f69
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
