# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/any
    REF boost-${VERSION}
    SHA512 92e50b8a08911e25ed172dbf03c6c05dade78c455f95fb1043821ed921d4b10eb9ba2ca6fc9e7f02ec88586d6b22d708219f98cf10120d4195cf6bad43bc8e65
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
