# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/any
    REF 8292e1831811488bee57feee690b818b0821cddd
    SHA512 1217ba42e34ea079a0216e391a7e36eaa5464a4510319141c79cbda4e8273b319d6103793fd8b43cf3ced352a7ef1d231f3e8e27fe7513065cc511587629dab0
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
