# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/scope_exit
    REF boost-${VERSION}
    SHA512 2395b8e8259540decce0e0fb6b543501d1c17bf0d34e60535950505a66a159f3f9f22b19982b2714243c31e9b29226c85cfc201c1864f7ed6bd4dbdbb1377c12
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
