# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/scope_exit
    REF 60baaae454b2da887a31cf939e22015b6263c9e4
    SHA512 60d6cb6a21acf782e7ad891854a86db36241138247fd8f52856e276f7b6942b9517152cfc81a2363bcc28d1b1ba1a949cf8f6cf2c732e1e4a5028e9a51b73d2b
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
