# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multi_array
    REF boost-${VERSION}
    SHA512 07520e93b18c22454d9db676e39e1dd311e65532e59c1fd9b20640d7c1808edc73266f5cda7d79adba3a066cf4e77368870916c712eb809f9d7225c22c3c9ae3
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
