# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/units
    REF 45787015dd8c11653eb988260acf05c4af9d42e5
    SHA512 a868c7ba0c81407c2454174276ad40fb6dc8cb4e659e9b08af24c00c638d2e0e0d26d195c9bd337d29fa9952e4777d4e35a0cf2d7793a8a62d375bdcd31e9797
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
