# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/move
    REF boost-${VERSION}
    SHA512 e526bf8a00510fd905e1962e3ffc6a22da950dec6b17d2744e8bd022c38e95bb7690e840d9e881234c3b4e570ed6615e9a911cdfe0912bd101b08de82b822727
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
