# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/move
    REF e9ff3ca0952e680871145f454925614d950cef4d
    SHA512 b7f17304fbb38c18f9b380547612602981ecd3fed37768c3132635148ad0335f2b0fd1ca6823515e44c89fbd3201f9980113a1f711ebda5dc335672b9fcd1f25
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
