# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/describe
    REF ddff876eeaab5f08844c4c8e88d1679f86ae8210
    SHA512 9077f767652c33b9a827384a39a896ffb974ff01ca1d10d2fa611274f09a11059302d76119aa4a1d8059543ff82acdfdcf9e3001050a6524d12d88f109d20b05
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
