# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/describe
    REF boost-${VERSION}
    SHA512 dd0e208b8f04f4160ff3922c17f5839f52274a7752852255095d5e2cc19eade9eee6bf7f010f7f655d70680292e4441637dd20a13ebd487ecf8e51ce8f5a39fc
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
