# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/crc
    REF boost-${VERSION}
    SHA512 13e097d706caa2b604a672fe5afd203ff319c9683079a38efaa0dd69c47c311d2f14850ad5cb94b1d08408365882f54deb56d2c856b5835edd05fc6e388e3493
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
