# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/crc
    REF 75146a958410c789381a4609166c754d35548e2d
    SHA512 6d1bb42d7e5c640a8cbdbea840e4eb45e2422e0ebc540d1274d8bae3058c5886cb521e0513eb10967f95b551344f9134596accccdd3a9c2f762b8e16be518b63
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
