# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/format
    REF boost-${VERSION}
    SHA512 03ea3111bb35744bf8ada6f0052f4b3ebfeedbc1a1c740e1dd316ae4f0c928da83dbdaa35cb9d1842876da0f1fdcefe575ea541ea7a56e9796a117bbb9c58db4
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
