# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/proto
    REF 7f924934689b940f3a72212ab0f714ec6fd6e34b
    SHA512 a61b4019ee99bc6c22451382ca1aeee59f1f1c09954bd78315c27970afee3b4ac995dfd26215539e0c7e1d92f46acc09a56797618bf8abbb40071d63fe4fa8c8
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
