# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/regex
    REF f851a08050dd6d4bdea552d2cf614c69d8d3cff9
    SHA512 b8b747247324c7233673c1e29be8d7f0d6aaffd66a2509cb40a4c0a225c4f6f9b54ff09a7c8d31a03e0a56d67a97914ea1627f354d7ebfd30bc0bbef6625d7b6
    HEAD_REF develop
    PATCHES
        compat.diff
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
include("${CMAKE_CURRENT_LIST_DIR}/features.cmake")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
