# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/regex
    REF boost-${VERSION}
    SHA512 0b1a3388c5ec870b46be478cf982059a943525fbacb5ba43a435e914e4fab212b036a29f069fa2ad973071341d4f8f4244d0e22332f7abfa416e4f93561d4c60
    HEAD_REF master
    PATCHES
        compat.diff
)

set(FEATURE_OPTIONS "")
include("${CMAKE_CURRENT_LIST_DIR}/features.cmake")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
