# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/leaf
    REF aff38b5be343ac6f1588e3258d126224e5347934
    SHA512 d1c7da743d22234ff988c2726816f5e513e8b8f2b6739be000575b5bd6c964ff88b2c5553c640c81e45cf08006c48692098e6f7cc31f94935a18fddaf1032c16
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
