# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/leaf
    REF boost-${VERSION}
    SHA512 459b4d0383138280aca7052190d631a8d8aa54e735d2a8e888cb3985d40438f9b545579a94c41fa1121badf4e8ede62113878a757fd9d3f185827683e942d845
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
