# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/xpressive
    REF boost-${VERSION}
    SHA512 b3a12aede0bbb47cbc37c8114da7975acd86fa39398b983f0036d79a4e4008ec67fe5049c80584f64bf1893523c95e4d0947c5bd420ed1d48757342149bf4991
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
