# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/xpressive
    REF bd1db9341abd303dacc2979422d8809a9a1e0558
    SHA512 5a0c3043c0c202ab61f04ecd48c785c4829743e28ffce6346d39c4e016fe42bc696dffa910c764d8e4fe8e4dfaf4e2f25b53e4479d71cac60f7cf9c58f6ce393
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
