# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/io
    REF 342e4c6d10d586058818daa84201a2d301357a53
    SHA512 59af1171c4c3cdfc0d2307347d48efa5f4f60565aa17c23ba0145ba929490e8993da4f1167579b4090d32714c5e1b5f5976d8229b0f43a0fadb53fe04bad69b0
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
