# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/io
    REF boost-${VERSION}
    SHA512 55c06cee3f36b88a44f1ac49e3a9f2b5eac980ccb89a8f6de60f53b3741806e9e26cc6f2f193cee01d80642da7fda1c1c6b8b8a5c4fbb7cba8c0681ce5183f4d
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
