# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assign
    REF b452220f5de0f6205433c08cee63742102a424d2
    SHA512 4725dbdbe2d9b20d0c42df6da9d693036a1d36b1d341d70af40f1eafed6d3c6e4b89bec38a7eb5cd3554114f5728c65f0f8ea8a3194d7832a4c3ef5cc0bc82de
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
