# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assign
    REF boost-${VERSION}
    SHA512 50f70b8edae02e523829fc39a3f6559d2f26a2ca90da5e85bcdd259fb4f6b19cb957c4bc6cc4c695c65d8553ff2653aee385b06a17feae2db2ca9844c8737ed4
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
