# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/date_time
    REF boost-${VERSION}
    SHA512 eeab0d2ba671bbe88b4a79f38b0ee4a12c8874d9123f327c351ca4265ed077b62296b8d9e843d6e85b3063b09ddda4fc876f6798dbf9294315150b986f185f17
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
