# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/range
    REF a18dbf5d3384444e23e3c65915c1f69981d026bd
    SHA512 5b5c3dbdad8c116ea2a4e2491b8ede64442449250cc2c8ddcd748e860b4a5dfd0ec8322abeca8ef2fdb234aa8911a4ac0f2ebaefca23c97426408f19f1a30f64
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
