# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/fusion
    REF 495539ce4404bde4af187ccc072235a6a7446e2c
    SHA512 a26d6b7c209b15079bb8312a2fa4c493a701d318f7e54609b237b15e9c5abe8cc6856a8bbec1dac57c9730519704a22a7f231ffe63794942ca497454d623112c
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
