# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/fusion
    REF boost-${VERSION}
    SHA512 5a97552cc02fcae793a34edb749b80107b82f2f2f28fb6388f168af093c295fea109ec6c6e609d64fbab922168b6ebe31b07119ce6d099a6eb95823d1b408720
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
