# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/redis
    REF boost-${VERSION}
    SHA512 ddd91338ce0de36e9c6b559988708891508b6c72e3aafb53030cb72f9b060ac7f90bd8be75a94b7583bd1c59fb74ed2d9a65c6da707c171d245994591f57cc59
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
