# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/log
    REF 724e888b5a558f8dc3db64b4397ce23f83baa53e
    SHA512 60f2fba6f5fb0ccd4b79e73397b776e9e0c8a48d82bdd6d9052b1bf99de0b62e62b1ee5474e530ed9808847e3914bf6a50323ac5798a67fd50b1121794a9b8a9
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
