# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/histogram
    REF boost-${VERSION}
    SHA512 3a4bab6ec9661b84c28521583b7890c94f22461ecd3d4b74697fa883ebb2e3117908a2d3eb5fbe4f154446832d30fffbae4f1acc2778d534bff9356cec3fdc25
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
