# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/outcome
    REF boost-${VERSION}
    SHA512 15b6a0b93b3e1eaef7f4eb5610d9cce5bffcf05fe43067b635541a5cc39ad2bba3c3eb51985b27ca113f064d154b20a68ceaf60db20cdca4b8490db76fd53066
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
