# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mysql
    REF boost-${VERSION}
    SHA512 24f57405768d97a2f9362c0e7ce57bdb945e4cd8aa703ea6fab64ee50293fd64d27e2b448eaf4a35523f940e58dc775aedb17d2c77f6f224ef17170911728c2d
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
