# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/url
    REF boost-${VERSION}
    SHA512 9cc5823d6100ca0aa983376b3ffd72eab6094e02736cb4291af737db191d74333476dbcf755ddb2b7bed6576d9d66d24f9f50245046ae7e5ca6e7d117573b05f
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
