# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lambda
    REF 593ddc73820a4b1cddf3e8e3f0b2eadc4aa2ab85
    SHA512 429b8d6633d5eafe7e2323331d6d8e713fedd4ae66c5572a167c5c01f5270c85df31041c3de1ee76e9c753147b901a9b3a750928e31a4ea60ce7e3603ab9dcd2
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
