# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lambda
    REF boost-${VERSION}
    SHA512 515d0fce6755574081e123ae06a6459e2810c7046eb5c994404a89d40434d1377d5b86996eec456660d7f5b160bd1e3ae0d94bc546c8716146260249341ca3e9
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
