# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/logic
    REF boost-${VERSION}
    SHA512 2afdbfad7f3f5324351838bff284d00626fc0e5734e0444a553ecaaa5081ac8aa381b66b7bfd342652e470a444f992cb02f2178fdbf91df99f9422314921e784
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
