# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/integer
    REF boost-${VERSION}
    SHA512 1d9f0b8edbd186698c057c0b606070d9993b5f1c7eb1736f5c8271ef7e3b8f37220d5531e301240f75ddb58f4e5fc997492aab74b651e2005da9fd77a146955b
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
