# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/parser
    REF a3ca1193b2e8b2c0100ae75705312ca240430e61
    SHA512 2276f41c88e01f2d13e7afeeaacd1b5ee984c4c63817b791e844f3e0ebee59686dd9f75c19a59724115138bdd9476e81b18e91a4a87f6b52da7b1583469925c7
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
