# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/poly_collection
    REF boost-${VERSION}
    SHA512 0c9082ee7120d992d1f0952e0f69ddfd6d714363ed20b205f8baf4c757335a94192c6b0fc19fa6329fb26e308d32ff2ea8af1d2be37816f4aeacd79964e2ac88
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
