# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/poly_collection
    REF bbdfaefc323ef1892107ae47ba87323eba4adb8b
    SHA512 7cc5ff2d11897ebead973fafa79a53c1f946cdfa13f4eeec1f9e0101dad6755c6adda494abbe113363cc7b49a202869f93fd2d61b4806eebff99fa8679f3b342
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
