# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/beast
    REF 1d8dfae490125bd63efedfa7a3ecf20e8e9b54a5
    SHA512 2906db94416d0e98a04ac566ecc9eb38c3a7567f716a3c57ec227b297628cf2cd9402d430e911c4a54f8be6ce03473a9c7ed017dd93ec3a5aaac1432bd0e4d26
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
