# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/winapi
    REF boost-${VERSION}
    SHA512 1daad939e0c46108e96bc26a088e86948be1f6eba8d1fb31acfb4b7be362b3d15a630ffa246824d03728ce753bc2f2e89622574268fd287bc1880e347b9c1f35
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
