# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lockfree
    REF e8d3374f6917ce41a8059dab8785c67bfe15d43a
    SHA512 9396204e3bd85f4f3ce811c019dd60d0f9817c6014bdfe5cee3e20f7967ada3e9e712153d289ff28a687f836d1ff08610bd5dee2fff43e71b00a9dd9ce4223da
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
