# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lockfree
    REF boost-${VERSION}
    SHA512 e65dbc248ac3deea35460e1f06976c013bdfea1d6dccd06b825bed1c13be7d545a75ea7403ee4ccdf03cf8542e5d6b3afc4e7d0dd477d79aef40dd7f9449fd40
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
