# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/gil
    REF boost-${VERSION}
    SHA512 cc35d92e9194bbd39771f150371034d0c0e59c1724ffbe180ef731d48b682b15aaffc47c06cddb97c6ae387199a2aeb50d900cf9d71d7a5eb0a0c6db34da963e
    HEAD_REF master
    PATCHES
        remove-boost-filesystem-dep.diff
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
