# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/gil
    REF 688acf78f7fc4ecb5b1c6f1e4a8f4a5939d28e9b
    SHA512 ac1b9f8226de2ac4721eecf3ceade42724f74d969c4d302278a3687b434a5affaf926222c4b4ed084a030634e7260836ef614e90f1e49e9391906f01dae20616
    HEAD_REF develop
    PATCHES
        remove-boost-filesystem-dep.diff
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
