# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_download_distfile(ARM32_PATCH
    URLS https://github.com/boostorg/json/commit/57d42f07158b8ea4a713378c90d22b28ca4787f8.patch?full_index=1
    FILENAME boost-json-arm32-57d42f07158b8ea4a713378c90d22b28ca4787f8.patch
    SHA512 d74a43dfc08fb34ba270a4d7de00a4307728567fbb2949f40f649c0e1c63b690d48aacfbc888e4b8075ff55262048700ab6ef669aa4277d6e9bebbbbd5e9473f
)
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/json
    REF 0b1048adf7571b42ae9f684b63e4383241b9e4a1
    SHA512 a13fcccbedc82a9af1c95de7941a3f6e038e4edcea681597823c38b1a65434f382a79506545a081ab4441bd6253acbbcf9602bae8826fb17288b75749b6b6d2a
    HEAD_REF develop
    PATCHES
        ${ARM32_PATCH}
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
