# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/context
    REF boost-${VERSION}
    SHA512 6c856509f9646e0ae9504960c2ca02233b26d0650cb7df0d710bd9d32dd8ad33fc8831bb7e8b63d7520af49c575f6cf55ab6370e49bf154d37b31d4eb1e6f983
    HEAD_REF master
    PATCHES
        marmasm.patch
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
