# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/context
    REF afd2ce33722e223d75723f3b44dc9fa94302e764
    SHA512 b7cb27b22c79c6db00351c658c99e8b233c059957510bc6ad35bd5b5a8d655f9e16b51d27e06ba685704c058545faa8b23c34a3255cb7a3ebe57dcf3a22402d3
    HEAD_REF develop
    PATCHES
        marmasm.patch
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
