# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/nowide
    REF boost-${VERSION}
    SHA512 e3eecfdadb5cddf4e12bc68b1b4f5d3b79c718b97a8e671bc7b8ce40220b8cb6dc688e31f14b7fe5a793c8c1c5926dd49c3223020a95cf463df5b2a07f0a614d
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
