# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/optional
    REF bfdf0c73f98efba4c2458c806b1af9458e4bf79d
    SHA512 aaede02655874d295e97dffd5cf5844dea774edeb216b6ea1499ddf12297b82cc96961b3e29023e208f3fb5a194e5cbe9d2ebe6edd826961f573851b13ac0771
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
