# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/optional
    REF boost-${VERSION}
    SHA512 fdeb9cdb68fd4e6895010da77eef4793892dcb7014bf1bca47d6386a3f54788dc04f698214b37b98727150ba6ee82779d8af59a3ade41bb3687dddaf3d75aade
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
