# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bind
    REF boost-${VERSION}
    SHA512 8816c8269e36c764f4c7c742603ace00c169f7a719c34415723da050c8ffdcbcf082839480b586b85d0fbecb873865fa03d62335da108ab859d5eb60916b4d88
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
