# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/parameter
    REF c142f7bdc27ed5abf945370c3bd82750fc0bdef1
    SHA512 9aa518e455d67a37972667e0cdc0241f769c5b7ee8c526d944db31e6ebc89ab0f636c204bfff492971a8e08f2215d83d66dd7f0e668a0fb346f02c5443a949ff
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
