# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO jll63/Boost.OpenMethod
    REF 0423a3968ecb4a39b64b1608d05cd7fefd2c2572
    SHA512 fe475bced6cd94b5ba60e8bbd1df4e4b9e3ac758c8d6d115177c5a429ec3185473f7aefb91fd3aa7c7abccaa4587cecc2b494107df690fbf9e2692a1a01928fd
    HEAD_REF master
    PATCHES
        cmakelists.diff
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
