# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/dll
    REF boost-${VERSION}
    SHA512 a26e91518465044b42537fa09f4b288045b6907b8fbc684fcb9b2cac609252f0d35a26ccd93f48141de6e79832a4269e870670efec44bb9297736ef65fddcc20
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
