# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/dll
    REF c30df76b0492827c6e3b6177c733f45987094426
    SHA512 8e9a4f47c383118a0da5f08d2b12c929e53383d93d0dd5959dc7b07fcd64bd72d4db2732f5a32e5fea547ddd92f67b7063bd11169f12e87d86f68e88b57a728b
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
