# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/compat
    REF boost-${VERSION}
    SHA512 d415f5a9bab41cdc94af2bd99e14d09f7f88c4ebe4be18e204bdbdef51e40df75e52f4b26d7250c4db0e29488dc06eaaf92b5b9dc420db77982a37b01464ccf9
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
