# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/rational
    REF boost-${VERSION}
    SHA512 5321c33820c16ee6c3dc7e57518cdb693d9c2b5ff7eca4a3d556c25959648471b414875e931bfd8c227e29dc5ae2e1e13933eb1c4f3c54bbbecdce6122cf59da
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
