# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/wave
    REF boost-${VERSION}
    SHA512 631779cd0bbaeb9a6bbf3c87415092c8bd4faae95fc6a417cbbea1c76667ebac4500bf53b1c5dfd4bafb90f2549096a9f7775b8191b8881b0335fe5ab09198bd
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
