# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/polygon
    REF boost-${VERSION}
    SHA512 f73646aa99232730ad81fd6eb237bc587afcc4c65e96a64f46760354a769f7d6c3519c4bc95701308ce55a78c29887fe8bf04d87328cc0a793fdce80d0ab067a
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
