# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/polygon
    REF 7aa8793414fc926dbc816cf6017dfa64c54da288
    SHA512 72eb61398816110433155c21fce04dfdab5bd6cdc223df608261eea4d0aaba7289b72870cb9c13b7d26720ffdf63da533498075c1095b8c355336b97f0f3cdcf
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
