# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hash2
    REF 14a374ea904cf7a58cfef65e11d1de067fe0dd82
    SHA512 302f8f7813fe844089b998f0c4859d84a6551c6ab6717e2e58e72b618f97f8599c79ae269591f897a0bce67ede0bc3e517dc17d6a316480da0f1c067c3b56294
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
