# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/filesystem
    REF boost-${VERSION}
    SHA512 26c8128296ab84e4f6e9d03fa1dfb4d32e94a9a332426b034e8d88686520be5974dec36e8bbd908d915c5170bc9ccbadd728255dd206a8a691c45f030fb7044a
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
