# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/filesystem
    REF c7e14488032b98ba81ffaf1aa813ada422dd4da1
    SHA512 b5d493ba201105f01c5e1e33dc0d1ca1d83b0e45022c92d91581d8df30d549f5c2972ffc44408114bf306ee576818d41ee04ecc70dce60a706cf1274842438e9
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
