# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/static_assert
    REF boost-${VERSION}
    SHA512 782528c9eaf9f151e7f184f10e5b75731ebaf70437798a40b1742be00302d496af4f86dc5f8a7b707f72757adb72bd1e8c277c6a08c5811f256228f6d5713af6
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
