# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/static_string
    REF boost-${VERSION}
    SHA512 d17e67c88571d088110971eaf6a3dca7d2d14689561f19cc7f3c6f927f18a9cf661ed898123b6c964ac7e273619e835f0d24cc1bd94492fc794fc22c86f4b064
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
