# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/variant
    REF boost-${VERSION}
    SHA512 474d52d1ab52dab22e21e9c01e6bc2e4a521ef5d9dbcd10ae53bcd4f713ec586c791c12198edbdbb540425a5baf0279ac1c8211d02036852e9ddc265a1ec702d
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
