# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/safe_numerics
    REF c46d7a33fa6efc10e3d35526e9fcf6673936ed41
    SHA512 d983a91338bb59714a9b43f097edb8e9305638809502db47e04d38092462c730e596a8bb2d52f8f4169bce54c61e0445afe2fc90721eb289e433f523b6090f5a
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
