# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/safe_numerics
    REF boost-${VERSION}
    SHA512 cd742c99c81c7c98db3408954cd4f469e8a9023d560adab7d28d83d868fc510f29f41a5578cfc002f5c3aab8625929e5feab0cd888c37320b3bdbeb713928cbc
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
