# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assert
    REF boost-${VERSION}
    SHA512 ea0fe8355c59f7745f30f365f29827a9149fa7ee50cbabbac014f912e1eb1298b8203fefba7df5d411b2744057ccdc58418fb8c6c61dfc95290e574148d0121b
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
