# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multiprecision
    REF boost-${VERSION}
    SHA512 3f59b792282fbc27eb21cff61dc627a750d520f1798ea149e59e9f0552bc862b6c114ef14a92bf7542d5e348eafbeb94136841104693f4f3220d2874f17f965a
    HEAD_REF master
    PATCHES
        remove-random.diff
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
