# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/foreach
    REF 904451bb8b094b426a69fbf33825c06677f2835f
    SHA512 86e804d2741080012ea25d0e4270de34825760814d186b616362fce2d5357188217a032a2176be6fccf1f84397c9202c750ad378cfad09581fd35c0bc0dff60a
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
