# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/pfr
    REF 3fe5ce61eee743c6da097c28bc0b84bdf29f6cc4
    SHA512 bed71ffdf33e2ddb643dc3620b6325865125bc110c39e6af41e56512f857ed3faa0dd6b24a91be1e9ba72dfb0e0c36b3319c4f5e3e12d299ad5e8943eaa88e5f
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
