# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/statechart
    REF boost-${VERSION}
    SHA512 6bbca61e0bc643c20a98f23b50c959658d089a6953576e8e6350107df84dab2e4af7e12c4af058e859945af2ed4bcb70219daf0a1329574fe81aab2dfed49266
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
