# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ublas
    REF 8934b49ebe5327964b42faefbb22334ba89f4574
    SHA512 65619e8357f62f7de27c98490c01c3ae2b6c58e0e46b99e5cce3da77fe490c4f6fc4fb20e3b1b93246b5b80393014f011f7a4c7e73e0e2cc7d179247dec44321
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
