# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ublas
    REF boost-${VERSION}
    SHA512 1836b2965a50688bca6102bffcacb792ab83dee6c43ca4e3ff0209b97359f25e45cc6809a803894f7f526915c0e8959e721818c0bd88ecaf7e2dc449b9d4be3d
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
