# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/qvm
    REF boost-${VERSION}
    SHA512 dc0c8ce81888e241eab4df679541f6b84f606d5884df65ea141b5561e81507e513cf77f1fa58599e975f3104aabdb69183971ce6248e30cb2e9e3e3fe8e9b7b8
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
