# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/scope
    REF boost-${VERSION}
    SHA512 87c44b1ed952d75aabeb0abf82af1ea452ed00b1bab594348368754b01252f321cac6ea81d00cde41af9a4b55686538d59b2e9df4077ffda2d5917fd300fb855
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
