# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/compute
    REF boost-${VERSION}
    SHA512 0bde764da69bfdacd3eba431c3ddb0293e8fa6708c3b48f6e423c3bbccf474936d53ca1f0d964bc1011d0a576c443087216b6373d5bcf86e0142866b7909d2f3
    HEAD_REF master
    PATCHES
        opt-filesystem.diff
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
