# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/vmd
    REF boost-${VERSION}
    SHA512 8e241e45bcc7b385bb3db05d1726e1d46e3be24a9febed49aeadca2ad7d453fd4391e44f68b724ad3650a35d30fcbd466a2a6bff83e9aa854876bc13c32ea0fa
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
