# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/vmd
    REF 34cad2c1a574d445812c7c2432d3a5a5c843b412
    SHA512 5e86ba5da4096375afaad952744937e6f2b88d88f30fb035674384dcc86121fe26e48584419321890af74f6de4a1cdb47bf64735b954703d7bdc13a8e25c7c0c
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
