# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/circular_buffer
    REF boost-${VERSION}
    SHA512 d0ddc6722f33adb52c623d7771192d95e681e89993cf1d890d6a06bdc60e5d194349651f3fbbd3c69e4dbe35567a897f0f4dcb36c305152677c48da337cea5b9
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
