# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mpi
    REF boost-${VERSION}
    SHA512 8c42a2c968e33881be54558471e894387c8fbae63d3e3a95e028e24572f010db6b86038f8637a1700bbb8cee06fc3d6fd0662d52283f93b8d78173bb58d37b57
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
