# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lambda2
    REF 865eb98c9ca7d37e95ed062c4d4197b15c1e3d18
    SHA512 a261de2f2973b4b777862ad82be568e863962ae362d0393f150fc5578e3c1b63faef8dd69e03166cd38dcf50649ae0dcf555543c85068788c89def4951c77666
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
