# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lambda2
    REF boost-${VERSION}
    SHA512 0d4ba6591cf449364a36653bddbbc7766675bfed7066f2875cc9f7c4687c98c4b15a43942c20e1b1549ed02964a9b70354ce13ea9814ad86d775f1ae46986a96
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
