# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/preprocessor
    REF boost-${VERSION}
    SHA512 af3b686b2b8c69b4b32ce15ddfec185b792d75924b0e45d6d329c2b01f80a3b945b85f383b6a8f4de4f627266d49a442eb3dd64e02f868fbd66f6ffdc2aadbc3
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
