# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/preprocessor
    REF d899a718f190e9823d37411819e89e8e4e535c37
    SHA512 23597cbc5207e0771935c6c7a741920db808175bef4b86d0c61ac53789b9bac5a44915d144f9d53b1ece704618310897c874597ea59260365c3b655dbb083f5e
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
