# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/geometry
    REF c08975488559cad0660d201b61360821f7814a47
    SHA512 e7c174b1aad8155648f716ae2fac2a7180de715f29d58524b2d35e6c0ff3c7a09387b62a0dc8298972eccac703fd34872c0048ee11dfdeb051de166d6e5e0698
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
