# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/geometry
    REF boost-${VERSION}
    SHA512 0fed33b04b2bf8927990fb5ec146d8ad39d3b3bce650dcf56dfc29d65940466af3f21917571bd22671bce45b72bd134b67778a6105d61dcc22ff1654f2c7287b
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
