# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/dynamic_bitset
    REF 688a99f54a3854f9abc26cde6afed3135132ac02
    SHA512 55c6c06196d23820c06bfd098e0c3ee138b66d3351d748c496eb7ce3b4e13e1312afeaee6fa009ecd798d9f010aa306ee737c6ad616fd1022736cace5e20e245
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
