# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/dynamic_bitset
    REF boost-${VERSION}
    SHA512 25df145ac2097b44a03b45b8eb0d1f2aa02b335fadf8e345fc02b1aae22fc0d2f5a68120b770d50f159cfc6b88e188cb884897749d0d653d8d4ddbf8e7d42db7
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
