# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_erasure
    REF boost-${VERSION}
    SHA512 f434bc1ded13ad9fd1579cc08e923293c8a21ca2085b4aa0a15f456c266bc1f7e556b46daef23c609bd4fa002326c6c10274795df5a456adfb5c84a870254ba3
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
