# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tokenizer
    REF boost-${VERSION}
    SHA512 8cdf640d60e8c2b0ba5463479faf344404b046f22c702e7ac402965030c3cd862d909b5edc8bbff6e29a4cd55e83c83a688517890d563ede7e27b9a9e6c99d6d
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
