# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/process
    REF boost-${VERSION}
    SHA512 cc563d7599a55ffb9f25ad10c8322ca80373781c7a2b8d9b87758cf84df1d31b20a8279279a0fff4168e04c7fe71d2c847d376dba2b28fa3a02d7633932513ac
    HEAD_REF master
    PATCHES
        opt-filesystem.patch
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
