# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/coroutine
    REF 8b09bf7d0e8a13d1ef59aaff02a84d42acb034f3
    SHA512 e21fbbefa6598fa342119f97155191bbd32911b8137c3c844d85b13901071806dbcea606cf85db216a835b836352584c05ee7200e88c2c81f5e24a36ed8c7e5c
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
