# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/coroutine
    REF boost-${VERSION}
    SHA512 234f01f95e70b4d31ffcb7b85a5b35d5f5c058779b87736dbb3c72dc8f734926a0639a4fc3f83f4042c3230caa1f2a9a2db0f306857140f46bf0c639c8a03ed8
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
