# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/timer
    REF boost-${VERSION}
    SHA512 ae1d769bec63ab8f154c26e738734447334a4c29714f4524bf813eccd652e28728cf8f1a2a3d7008c7b51a41aeb1d3348b666e1d1b84f027360cbf7f215a1e0f
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
