# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/timer
    REF b7f65f09a0975f26cb294eebd8b17e91a5beff3f
    SHA512 ac62e162162438de3cce0442294d9e3eb03c6365c4d7b05b16bc6825b4de3044d40017185c7a269e560048bd50b880254a823ca31f92330995960e1fb05f8907
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
