# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/convert
    REF boost-${VERSION}
    SHA512 6d934ca989ccc14679d250380f8835285c5540bef73fdc1fecb667ee87eff5576c7bd1d300725f451a905f4138d7262011ae05a1ed5dbdbc4d62f8ca015daf5c
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
