# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/typeof
    REF 426e7505cdca6356baca998e9e30fb148e3a78d5
    SHA512 0bf816a826a1339378ff06c3a8c5e1b820cd558126bb607b194069827eda4f0a5fe1cc32bd4274701531259bb4c3f7cabb60619dc6adeca1c897c876fc70f146
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
