# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/local_function
    REF boost-${VERSION}
    SHA512 fbd1032257dd860232aa7f405af7d54b05fc44945fbc2d8bb005212ca2f0212740699517a769d20d4af1a24875264f63ed2eba3cb5521c3bf45b82b9d3acd0e4
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
