# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/local_function
    REF 258aeaa6c1a9618c02ca4e4af2890e70833035f0
    SHA512 1a0ac58c1da0111e4c9cb707a029df5491e33aba6329f32a478917ca03de7cab1973b9c0673341efc07f7eabeae2bab123de717e4e85ee4a30383f18153443c9
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
