# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/signals2
    REF boost-${VERSION}
    SHA512 ec15fe63f88429839f07ce1a8109a84ff2a9ac4c63b8eb309b5a6562ee182390633f9d2f225d0859b3ae1158c1f135ec27baa46b260d221b119f83291b3fde02
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
