# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/pool
    REF 740c8076f9d02f0216e8f3dbb15d2fd80f67d7f4
    SHA512 c42038148cd0f0077629861a69d7578d8256186c0994d93757d5d1bddcefd80c6514ec0343f5a07843f12f5c68cd46cc2752ba701f789bd727ca6263caaec393
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
