# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/pool
    REF boost-${VERSION}
    SHA512 cc205aeb76e73431500ca6b34d7674eb52d5d20aa9a5559410ac2a131129497705517dc04d14cb5145d614b9d0b9cad50f2151bef8b1ab22c2d8adfabf433bdb
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
