# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/graph_parallel
    REF boost-${VERSION}
    SHA512 908cce78e7d10f19eb77976db247ed5b438d6d353571323fa128141ccf020c9b81d987d25007a07a60b9887baf37ae7d733758d036db176ce173a448fcf1a643
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
