# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/graph_parallel
    REF 39ef1fd1ef29fca367b95f9583ff99756eae8a0a
    SHA512 dec4fc0bafae33bbe085474af0383097c86e22ad969d06ab0027785a244eb7e7f507d54027f0af35c775c7157661953f8862356f94fc867977007765b8177125
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
