# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/core
    REF boost-${VERSION}
    SHA512 5b6f5d8520c46aaa0751024cef88f4bf823779da1cbb6d5aefe0ec97b98015ad40763d20ef48a13ae6bbe2d98ea41067d8347b748e6a380e75abfc20dba54b20
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
