# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/concept_check
    REF boost-${VERSION}
    SHA512 9c49578bca25ffead5584cbfd5ceead3c524599aa014ac7d9e4e246170f3417f0a4f80229eb4470bc40d49b0091ff39c2e9a4579d769e6e025aa232bc4ddcf53
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
