# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/math
    REF boost-${VERSION}
    SHA512 43d1d34a16c9cfebad7de838f2ac0ba12fcca26dd8c09289416a07178ba4e213ed7ba6a3f015a4e3acdff46d7e3bb1d96a1572129265a6f63fe0f2672d23c0e5
    HEAD_REF master
    PATCHES
        build-old-libs.patch
        opt-random.diff
)

set(FEATURE_OPTIONS "")
include("${CMAKE_CURRENT_LIST_DIR}/features.cmake")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
