# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/math
    REF a5c062542afb2037054c4e1b1be44db7b0859c38
    SHA512 46a7093141d1fa32fe78f56d9a42e0d14c793605d573ceddbd6f6d295b364179109ef4fb779e8e767dc2b195dd76387970bc19d178e4865775781624e5fb9af4
    HEAD_REF develop
    PATCHES
        build-old-libs.patch
        opt-random.diff
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
include("${CMAKE_CURRENT_LIST_DIR}/features.cmake")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
