# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/function_types
    REF 6fba35ace59e9e7b1c3007ca6246a42ed6ead145
    SHA512 b1778309ed4a58f39ddd81d5a27516638ac09ac45eed42efd4af49b68910b97d022b5b0929b2917dd2a757780c9b01c5d13bb45034206968d667fdd9257a6e70
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
