# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/function_types
    REF boost-${VERSION}
    SHA512 0cdd06cd6913028d8e3a525ce365046b924f5ab039fe846a8e8129099c0933b4ba893dd4a03256109cb438b8ad67e988525c6a6437a507e7e8b8e9daebb9cf31
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
