# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/thread
    REF boost-${VERSION}
    SHA512 d66e3e5540ad7db9a07150a26db20de7397570368db12e32d18ced257500224d2c69d4a280c67aa4753f987e75a5c40b109ae58bbe8cf5ce77b899f10531b710
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
