# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/thread
    REF 5d68c9c42ca7d3286b534b307c211ef8d7d76631
    SHA512 ba0b9cc8f9a11b7876c27f8997368a784936ef36cb4f2fa68e4b328f31481b8e4beac21457422ff07ce184908fa070837ef2eb203ba6be48171439bde3779635
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
