# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/algorithm
    REF boost-${VERSION}
    SHA512 0aa482c0baa4b4dba7198f8770b66af28f0ee1d8366f71e897ba357b51aa7b7d3b03d6c0fe1ada41943a26e3266b4f855b0dbc45959466dfa579326f4cb85647
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
