# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mpl
    REF boost-${VERSION}
    SHA512 cb927488a7cd48e90736d0c7674ccd4a80f477f7be57f1953400c17c125b352b8455a4e89b36ca93a2eaedd0d5728cb4ada7f0454f9ad385bc8b82ecc06837fd
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
