# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/flyweight
    REF a4fee292a5a71733796371443754849b2de62e5a
    SHA512 b6402b066e30e8f238c3669053d6023379acb0df426fbb61aefc3fbc0760804a4f76665501e5402b87927b01b1ead8254cdfa6339b7544459f63caa716ed5ff2
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
