# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/charconv
    REF boost-${VERSION}
    SHA512 4f45326d4466d434c3a16b2c1752671405701d06cf0096f6a699afba77c66e3b97eca3233ee139ae170d9fc64c2e8faab387215b0ab6630da3d553697ba4f7dc
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
