# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/yap
    REF boost-${VERSION}
    SHA512 62d108ca3e9a8e5e42ece482ebe52a6cc2d0d333e21b2d26c34de8f784a8a658f5af2af85ba26d5148f6b4a7710ac0c1d2cf797366d25ca4cf66296a4a1d1677
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
