# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mp11
    REF e5da96b9b655fd0c310136b88f90f6243ce5705f
    SHA512 e88f5a441423abed65a9463248b0e93ec92353086b1af095a4fec6587fd543f058483386b44c8b2500c4f67ef7c0b6fc62d2a811dd01def0905f67af67398d44
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
