# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_tree
    REF boost-${VERSION}
    SHA512 cc775cc5b942c05b155c0f79dbb92508adc72f1db8178b2950c107f12307b834d2ee20ba920ad0d060ea88a8d9a33b7957c61325b12da8129224390bdd178416
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
