# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_tree
    REF 8080ecd14f2d952a4bb7ae869fc0f54f54f5a31f
    SHA512 9dd95bc0153bf44400f5d61e0397e3ab0e64accf7419d99289b9563f2193bca069e8463e19b04478637eaa41224cd64422c86b42a3b0c6bd46daa55c14d5548e
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
