# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/container
    REF b13c1fe8a4921328c9ecdbdfc90431d73b2060ac
    SHA512 8aad67526ed7940705521160336c132152799f36348a4ca4fd166ff7c052af522276baeb69fd898d530c8212673d5cd1e8e66abc657834b6e6a45f82aff5e5df
    HEAD_REF develop
    PATCHES
        posix-threads.diff
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
