# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/container
    REF boost-${VERSION}
    SHA512 7d679565a443eeb51d32513d3435fadf6eecf6748a9e9d14d6d0194ec0032509258d2aa6e0b8eb9b39bf57622f8f907fc3d9934c53679fe9e385513dcbf44f8e
    HEAD_REF master
    PATCHES
        posix-threads.diff
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
