# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_map_parallel
    REF boost-${VERSION}
    SHA512 de8c3a39f4fff3c4e9dcad15d882cd9591d45c239981e099ba763d613cfa5add25621f0edb2e6cea2b1a29b59c630b74f1dd4ebbdadd00299c2fe24135d02d33
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
