# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/metaparse
    REF 0ef448c1a7ce22b5de514f9cd504c323c28f4379
    SHA512 34c3240408b0d525e916bfc84dc6e5592ea056e572dcc81499d72f17c252c740ed04b2f8534c71c59c4b5e71542a355308e117b8d6f6ed39361c57bea8dd83f0
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
