# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/metaparse
    REF boost-${VERSION}
    SHA512 ee6c3a6e64c658c104b6a6c15cd53e2314883c6c3d238f3a57d208767af98f6d5e7c1c5314dcd05645a19a262cd6e8363d6c7163681ed6c863302fb49d9f87fe
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
