# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multi_index
    REF boost-${VERSION}
    SHA512 90714eefa56f0dc0a478bcf0eb7c6838f12982a33844a0ae86fb1737cd7f9cd30e64cc9a98d9a124583d3f673f20c257541f50f1c136cba5eee3addf5adf265f
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
