# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multi_index
    REF 07eb41065d57f243b522ef6e8b469f47e8c2001e
    SHA512 83f8c3dbfb1e0fdca5fed646f53e03e25019d4889e5786cbd01264e4f093dd86e2dd614d777fb1fc8e2dc0bbe698c2ac56dbc152995699cce4daeeb88ddc3143
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
