# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_buildpath_length_warning(37)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/system
    REF boost-${VERSION}
    SHA512 f016fe9248e9131e2df76207961984dc11ba4f7bf3e3d7618c35574ff1e5fd30af6f7cebba2c64adafab875b859debb4d294ac785bed4b291d31116f5a372aa7
    HEAD_REF master
    PATCHES
        compat.diff
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
