# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/graph
    REF boost-${VERSION}
    SHA512 a0b556aeb2227416b85dee5693a4aeed2ad53a230a5587ae2b7bcd507749411b0eec44b0bea1e37f62c17c2a0d6e21ce2253a4c6441580fb1597a70e72f0743d
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
