# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_map
    REF boost-${VERSION}
    SHA512 66930121cb69bdfce5aa0eb2b65d5c98a8a22084c482662bbb44e229ac2d6b8b5aa6b201304647b923ea212b0f1413cba5d7fd8056bab0be1ac287e34b5b4cc8
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
