# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_map
    REF 830cb6bce0b54fc1b2d7806901c1b8c8716964b7
    SHA512 0c58a47850455e9340c86e01df41feb8b31c4b37d92be43a30da12e82db0fe666583cc957b28ea112c829ee228a5bfd0911b8d53339452ff64b3137c6dc98751
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
