# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_download_distfile(ARM32_PATCH
    URLS https://github.com/boostorg/interprocess/commit/f58e968f13e693ffaa78fb283972e8598dc48c9f.patch?full_index=1
    FILENAME boost-interprocess-arm32-f58e968f13e693ffaa78fb283972e8598dc48c9f.patch
    SHA512 7e9b5ebac8ef3c04327c29bad9b8b6259320fd9ebec80bac905b7bd4f68e5cb4f001e2c80f83a875cc12376df4f3b444b34251ac3ea88962982a147432ef0f7c
)
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interprocess
    REF 061bc6f8dfc2af90d9996a77317b21398f6bdda5
    SHA512 c6da40e26bcfd88f61e9041db1b53ebdc92c5cdea40cf22f0c729da65d5ed9a3fa223a6a4fe20ecc6052bea487e3326a70a0ee1b20267c8010aa8120db6a8ea2
    HEAD_REF develop
    PATCHES
        ${ARM32_PATCH}
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
