# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_download_distfile(ARM32_PATCH
    URLS https://github.com/boostorg/interprocess/commit/f58e968f13e693ffaa78fb283972e8598dc48c9f.patch?full_index=1
    FILENAME boost-interprocess-arm32-f58e968f13e693ffaa78fb283972e8598dc48c9f.patch
    SHA512 7e9b5ebac8ef3c04327c29bad9b8b6259320fd9ebec80bac905b7bd4f68e5cb4f001e2c80f83a875cc12376df4f3b444b34251ac3ea88962982a147432ef0f7c
)
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interprocess
    REF boost-${VERSION}
    SHA512 2ab71f9d34af2dfabe807e7e696bfb0089d0eff3aad9d17b0c8b5ac1487f865cd458b41bbf229a6d29bb4b1f4a1507aba95c48c7c64dba317d608813be2c4fbf
    HEAD_REF master
    PATCHES
        ${ARM32_PATCH}
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
