# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/icl
    REF boost-${VERSION}
    SHA512 de97f1bb5687d4f0eb40c529a8abf6b0edaa84c5730acbd17356f5ce690907e7844fb809a81cc72a81917fd9545e7322884d52878f33e8b227f98325dc799481
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
