# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_download_distfile(ARM32_PATCH
    URLS https://github.com/boostorg/unordered/commit/07f6463c1c302c5b1d28aa253e0b768e71c90235.patch?full_index=1
    FILENAME boost-unordered-arm32-07f6463c1c302c5b1d28aa253e0b768e71c90235.patch
    SHA512 99f631e57b0c7d8d08f32d994c34dbca2588b409c10ad35500c36dc5374dba91888ee5ba3ca7ed24fa75539e9d44ffc123892d859a736f63ca0ae5fffee2c178
)
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/unordered
    REF boost-${VERSION}
    SHA512 eacd9544cdd4061553928c6e662df905ad97e7a5c2dd91e7fd8c0c53354a666b4accecf76f61fa230bbcf90e0371a2ef7201031adfae697a458c1d30b9bd5c05
    HEAD_REF master
    PATCHES
        ${ARM32_PATCH}
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
