# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/unordered
    REF 3d2c63f744809cdb4d41047329fc9c4893b6cc8d
    SHA512 b0ad3d39cc964ea5efb76ab3d459032dee59268dd7f045c98f7d680b75a2b4060189a7554cd2f35966babf1acec3028ef66eb19ab99fd399dbd0d1508f72776c
    HEAD_REF develop
)

set(VERSION 1.88.0)
set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
