# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ptr_container
    REF boost-${VERSION}
    SHA512 0644add89cf4a59f5bf417ce1bff1e0a937672782f3d44f7d5332631bb3b9deba814f11e799615a5e83715b139f875411600fef97b09b693bd672114ead4ce59
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
